apiVersion: v1
kind: Pod
metadata:
  name: pod-con-secret
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep 3600"] # Il Pod resta attivo per 1 ora
    env:
      # Variabile d'ambiente USER_SECRET che prende il valore della chiave 'user' dal secret 'credenziali'
      - name: USER_SECRET
        valueFrom:
          secretKeyRef:
            name: credenziali
            key: user
      # Variabile d'ambiente PWD_SECRET che prende il valore della chiave 'pwd' dal secret 'credenziali'
      - name: PWD_SECRET
        valueFrom:
          secretKeyRef:
            name: credenziali
            key: pwd