apiVersion: v1
kind: Pod
metadata:
  name: pod-due-grosso
  namespace: test-quota
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    resources:
      requests:
        cpu: "200m"      # Chiediamo 200m, ma ne sono rimasti solo 100m!
        memory: "30Mi"